### ISSUE TITLE
yo code not working

### ISSUE THREAD

**Issue by SlumberDemon** [microsoft/vscode-generator-code#315] opened 2021-11-05 07:42 UTC
error:
------
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`, `${prefix}/*/index.cjs`, `${prefix}/*/index.mjs`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70:27)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:130:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:89:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:219:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by aeschli** [comment] 2021-12-06 18:56
Duplicate of https://github.com/yeoman/yo/issues/678.

node 12 is required

**Closed by aeschli** 2021-12-06 18:56 UTC
