### ISSUE TITLE
Can not lunch the example extension "hello world~" , it show some error.

### ISSUE THREAD

**Issue by Aaronphy** [microsoft/vscode-generator-code#241] opened 2021-02-07 09:49 UTC
![image](https://user-images.githubusercontent.com/16236806/107142797-4500d900-696c-11eb-8dd9-cad512966f5c.png)

Reproduce Steps:

1.vscode Version: 1.53.0 

2.platform: macOS Big Sur

3.yo and generate the example extension
  ```bash
	yo code 
	choose ts extension
	whether bundle or not 
  ```
4. Press F5 to debug the example extension "hello world"

However, when I run 

``` bash
	npm run compile 
		or
	npm run watch 
``` 
it works fine. 

I hope it can debug normally as the doc says, please help to see and fix it.

This is my vscode ```setting.json``` config about the terminal :

```json
	"terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.inheritEnv": false
```

**Comment by aeschli** [comment] 2021-02-26 10:31
It's a duplicate of https://github.com/microsoft/vscode/issues/76542

**Closed by aeschli** 2021-02-26 10:31 UTC
