### ISSUE TITLE
Error code Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode-generator-code#281] opened 2021-05-20 03:27 UTC
As I was following the VS code plugin/extension tutorial here [Your First Extension | Visual Studio Code Extension API](https://code.visualstudio.com/api/get-started/your-first-extension), I got the following error. 

```
> yo code

? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? HelloWorld
? What's the identifier of your extension? helloworld
? What's the description of your extension?
? Initialize a git repository? Yes
? Bundle the source code with webpack? No
? Which package manager to use? npm

Writing in C:\pg\vscode\helloworld...
Error code

Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\generator-code\generators\app\templates\ext-command-ts/vscode
```

Simply the command I ran is, as the tutorial, 

```
npm install -g yo generator-code
yo code
```

I'm on Windows 10 elevated Powershell. What's wrong with the error and how to fix?

**Comment by aeschli** [comment] 2021-07-02 14:03
I'm not able to reproduce. Can you still see it?

**Comment by aeschli** [comment] 2021-09-22 12:41
Closing due to lack of additional infomation

**Closed by aeschli** 2021-09-22 12:41 UTC
Labels: needs more info

**Comment by jharajnish30** [comment] 2022-10-05 17:49
Same problem with me too..!!
Tried uninstalling/installing the package and executed the command yo code
But with multiple reties ends up with same result
I can share my system remote access if required - if you can't reproduce it on your own..
Kindly advice.
