### ISSUE TITLE
`yo code` freezes when creating a color theme

### ISSUE THREAD

**Issue by dpinela** [microsoft/vscode-generator-code#174] opened 2019-06-20 18:07 UTC
To reproduce, just run `yo code` and select "New Color Theme". `yo` displays the TextMate color theme import prompt, and then immediately hangs. It won't even react to Control-C, although `pkill -INT yo` from another terminal will kill it.

OS: macOS 10.14.5
Node: 12.4.0
yo: 2.0.6
generator-code: 1.1.50

**Comment by HoLLy-HaCKeR** [comment] 2019-06-20 18:51
duplicate of #174

**Comment by dpinela** [comment] 2019-06-20 18:53
@HoLLy-HaCKeR I too suspect the underlying issue is the same, but I'm not sure, since I'm not familiar with the code.

**Comment by Happy-Ferret** [comment] 2019-06-21 08:24
I can confirm it's the same issue for all kinds of extensions.
I ran into the issue while attempting to create a snippet extension. Rolling back Inquirer fixed it for me.

**Comment by aeschli** [comment] 2019-06-25 10:05
dup of https://github.com/microsoft/vscode-generator-code/issues/173

**Closed by aeschli** 2019-06-25 10:05 UTC
