### ISSUE TITLE
preLaunchTask issue for .ts extensions

### ISSUE THREAD

**Issue by Apidcloud** [Microsoft/vscode-generator-code#105] opened 2018-02-16 18:00 UTC
Good afternoon!

Upon trying to debug https://github.com/ericadamski/vscode-carbon_now_sh (see https://github.com/ericadamski/vscode-carbon_now_sh/issues/8), I have noticed that the following command is not working properly (`"preLaunchTask": "npm: watch"` in `launch.json` for `.ts`). 
So basically it doesn't produce the output and therefore doesn't open a new window with the extension.

Running it manually does the trick though: `npm run watch`.

Tried a hello world ts extension and the behaviour is the same.

Thanks!

**Comment by aeschli** [comment] 2018-03-02 16:11
I can't reproduce. 
- run 'yo code', pick 'New extension TypeScript', enter name 'abc'
- open 'abc' in vscode
- go to debug viewlet, launch 'Extension'
- open the terminal view and observe that there's '1: Task - watch'
- in [Extension Host Window] run 'Hello World' command
- Debug console says 'Congratulations, your extension "abc" is now active!

Can you check what's printed in the terminal view?

**Comment by andymaster01** [comment] 2018-03-02 21:43
This just happened to me. The problem: my powershell profile was using the set-location by default, so the npm watch was trying to run in a different folder. @Apidcloud Maybe check if your bash or powershell is changing the default folder.

**Comment by Thiht** [comment] 2018-03-08 14:00
I had this problem too. I managed to fix it by adding `"label": "npm: watch"` to the watch task in `.vscode/tasks.json` :)

**Comment by FabienTaillon** [comment] 2018-05-03 14:54
I also had the issue.
This seems to be related to vscode locale. Using it in english was working, but using it in french (my default locale) wasn't.

@aeschli I guess if you try exactly what you did but running vscode with `code . --locale=fr`, you should be able to reproduce.

@Thiht thanks, this worked for me :)

I guess this should be fixed in the code generator anyway.

**Comment by houfeng0923** [comment] 2018-06-05 02:41
i had the same problem in macOs (win10 is work well).

**Comment by neet** [comment] 2018-06-05 07:14
I had the same issue on vscode `1.23.1`, macOS `10.13.4`, node `9.11.1` and npm `6.1.0`

**Comment by dbaeumer** [comment] 2018-06-05 07:44
The French locale issue is know and tracked here: https://github.com/Microsoft/vscode/issues/50799. The problem is that in french locale the label is `npm : watch` and not `npm: watch`. You can fix that for now by changing the preLaunchTask to `npm : watch` or by adding a label.

@andymaster01 you can add an option setting to the tasks.json that specifies the shell to use and then pass `-NoProfile` to PowerShell.

I ran the generator today as @aeschli did and in all other cases it works correctly. Can someone please provide an example of when it is failing in their setup if not covered by the above cases.

**Closed** 2018-06-12 09:43 UTC
Labels: needs more info
