### ISSUE TITLE
alway building and can't start extension host window

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-generator-code#214] opened 2020-07-06 14:53 UTC
I use this generator to generate an extension project. When I run debug, it seems that becasue the `defaultBuildTask`:  `npm:watch` had not completed, the extension would not open the extension host window.

```
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
```
"devDependencies": {
		"@types/glob": "^7.1.1",
		"@types/mocha": "^7.0.2",
		"@types/node": "^14.0.14",
		"@types/vscode": "^1.46.0",
		"@typescript-eslint/eslint-plugin": "^3.5.0",
		"@typescript-eslint/parser": "^3.5.0",
		"eslint": "^7.4.0",
		"glob": "^7.1.6",
		"mocha": "^8.0.1",
		"typescript": "^3.8.3",
		"vscode-test": "^1.3.0"
	}
```

![screenshot_2020-07-06_22-44-48](https://user-images.githubusercontent.com/41773861/86607136-78951280-bfdb-11ea-9ac3-083a700dc939.png)

**Comment by Shantu58** [comment] 2020-07-10 16:13
I experienced the same and updating VS Code to version 1.47 fixed it for me.

**Comment by tjx666** [comment] 2020-07-10 16:26
@Shantu58 Version 1.47 still does not work in my machine.

**Comment by hyeongyun0916** [comment] 2020-07-30 01:33
I experienced the same.
I'm using vscode `1.47.3`, windows 10, node `v12.18.3`, yo `3.1.1` generator-code `1.2.19` and npm `6.14.6`, tsc `3.9.7`.
I also tried changing the typescript version to 3.8.3.(In version 1.2.19, devDependencies.typescript specified 3.8.3 in file generators/app/templates/ext-command-ts/package.json) But it doesn't work too.

Possibly related: #117 microsoft/vscode#49756

**Comment by aeschli** [comment] 2020-10-30 10:00
Closing as I can't reproduce.

**Closed by aeschli** 2020-10-30 10:00 UTC
